apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '{{ .Values.service.targetPort }}'
    spec:
      containers:
      - name: fastapi-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: API_KEY
          value: {{ .Values.env.apiKey | quote }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10